kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: etterlatte-kafka-manager
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/kafka-manager:2023.12.13-06.32-bd9f95
  port: 8080
  webproxy: true
  ingresses:
    - https://etterlatte-kafka-manager.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  secureLogs:
    enabled: true
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1  # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure: # Required
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 650684ff-8107-4ae4-98fc-e18b5cf3188b # Required for authorization
  kafka: # Optional. Required for Aiven
    pool: nav-dev
  env:
    - name: APP_CONFIG_JSON # Required
      value: >
        {
          "topics": [
            {
              "name": "etterlatte.dodsmelding",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }
