apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: etterlatte-notifikasjoner
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 320Mi
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
    - name: BRUKERNOTIFIKASJON_KAFKA_GROUP_ID
      value: "etterlatte-v1"
    - name: BRUKERNOTIFIKASJON_BESKJED_TOPIC
      value: "min-side.aapen-brukervarsel-v1"
  accessPolicy:
    outbound:
      external:
        - host: "kafka-schema-registry.nais-q.adeo.no"