apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: etterlatte
  name: post-til-kafka
  namespace: etterlatte
spec:
  image: ghcr.io/navikt/pensjon-etterlatte-felles/post-til-kafka:<versjon>
  kafka:
    pool: nav-prod
  env:
    - name: KAFKA_TARGET_TOPIC
      value: etterlatte.etterlatteytelser
