---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: ey-slackbot
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_alive
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi
  ingresses:
    - https://ey-slackbot.ekstern.dev.nav.no
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
  env:
    - name: PORT
      value: "8080"
  envFrom:
    - secret: team-etterlatte-slackbot
