apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: dodsmelding
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  pool: nav-dev
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 48  # -1 means unlimited
  acl:
    - team: etterlatte
      application: dodsfall-fra-leesah
      access: readwrite
    - team: etterlatte
      application: finn-etterlatte
      access: readwrite
    - team: etterlatte
      application: sjekk-alder-etterlatte
      access: readwrite
    - team: etterlatte
      application: journalfoer-soeknad
      access: readwrite
    - team: etterlatte
      application: selvbetjening-api
      access: readwrite
    - team: etterlatte
      application: innsendt-soeknad
      access: readwrite
    - team: etterlatte
      application: sjekk-adressebeskyttelse
      access: readwrite
    - team: etterlatte
      application: etterlatte-kafka-manager
      access: read
    - team: etterlatte
      application: bpc-explorer
      access: read
    - team: etterlatte
      application: etterlatte-notifikasjoner
      access: readwrite
    - team: etterlatte
      application: etterlatte-fordeler
      access: readwrite
    - team: etterlatte
      application: etterlatte-overvaaking
      access: readwrite
    - team: etterlatte
      application: test-fordeler
      access: readwrite
    - team: etterlatte
      application: etterlatte-opplysninger-fra-soeknad
      access: readwrite
    - team: etterlatte
      application: etterlatte-testdata
      access: write
    - team: etterlatte
      application: etterlatte-opplysninger-fra-pdl
      access: readwrite
    - team: etterlatte
      application: etterlatte-behandling
      access: write
    - team: etterlatte
      application: etterlatte-utbetaling
      access: readwrite
    - team: etterlatte
      application: etterlatte-tilbakekreving
      access: readwrite
    - team: etterlatte
      application: etterlatte-vilkaar-kafka
      access: readwrite
    - team: etterlatte
      application: etterlatte-oppdater-behandling
      access: readwrite
    - team: etterlatte
      application: etterlatte-gyldig-soeknad
      access: readwrite
    - team: etterlatte
      application: etterlatte-beregning
      access: readwrite
    - team: etterlatte
      application: etterlatte-grunnlag
      access: readwrite
    - team: etterlatte
      application: etterlatte-vedtaksvurdering
      access: readwrite
    - team: etterlatte
      application: etterlatte-avkorting
      access: readwrite
    - team: etterlatte
      application: etterlatte-opplysninger-fra-inntektskomponenten
      access: readwrite
    - team: etterlatte
      application: etterlatte-brev-api
      access: readwrite
    - team: etterlatte
      application: etterlatte-brev-distribusjon
      access: readwrite
    - team: etterlatte
      application: etterlatte-hendelser-pdl
      access: readwrite
    - team: etterlatte
      application: etterlatte-api
      access: readwrite
    - team: etterlatte
      application: etterlatte-opplysninger-fra-medl
      access: readwrite
    - team: etterlatte
      application: etterlatte-statistikk
      access: readwrite
    - team: etterlatte
      application: etterlatte-vilkaarsvurdering
      access: readwrite
