---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: etterlatte-proxy
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    timeout: 1
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  ingresses:
    - "https://etterlatte-proxy.dev-fss-pub.nais.io"
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/dev/srvetterlatte"
        mountPath: "/secrets/srvetterlatte"
  azure:
    application:
      enabled: true
  webproxy: true
  env:
    - name: STS_SOAP_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: TILBAKEKREVING_URL
      value: https://cics-q1.adeo.no/oppdrag/K231CW80
    - name: SIMULERING_OPPDRAG_URL
      value: https://cics-q1.adeo.no/oppdrag/simulerFpServiceWSBinding
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: etterlatte-tilbakekreving
          namespace: etterlatte
          cluster: dev-gcp
        - application: etterlatte-utbetaling
          namespace: etterlatte
          cluster: dev-gcp