---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: etterlatte-proxy
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  team: etterlatte
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - "https://etterlatte-proxy.prod-fss-pub.nais.io"
    - "https://etterlatte-proxy.prod.adeo.no"
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/prod/srvbarnepensjon"
        mountPath: "/secrets/srvbarnepensjon"
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  webproxy: true
  env:
    - name: STS_URL
      value: http://security-token-service.default.svc.nais.local/rest/v1/sts/token
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    inbound:
      rules:
       # - application: finn-etterlatte
       #   namespace: etterlatte
       #   cluster: dev-gcp
       # - application: sjekk-alder-etterlatte
       #   namespace: etterlatte
       #   cluster: dev-gcp
        - application: selvbetjening-api
          namespace: etterlatte
          cluster: prod-gcp
        - application: journalfoer-soeknad
          namespace: etterlatte
          cluster: prod-gcp
        - application: sjekk-adressebeskyttelse
          namespace: etterlatte
          cluster: prod-gcp
        - application: etterlatte-brev-api
          namespace: etterlatte
          cluster: dev-gcp