---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: etterlatte-proxy
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    timeout: 1
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  ingresses:
    - "https://etterlatte-proxy.prod-fss-pub.nais.io"
    - "https://etterlatte-proxy.prod.adeo.no"
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/prod/srvbarnepensjon"
        mountPath: "/secrets/srvbarnepensjon"
  azure:
    application:
      enabled: true
  webproxy: true
  env:
    - name: STS_SOAP_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: INSTITUSJONSOPPHOLD_URL
      value: https://inst2.intern.nav.no
    - name: INSTITUSJONSOPPHOLD_AZURE_SCOPE
      value: api://prod-fss.team-rocket.inst2/.default
    - name: TILBAKEKREVING_URL
      value: https://cics.adeo.no/oppdrag/K231CW80
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: selvbetjening-api
          namespace: etterlatte
          cluster: prod-gcp
        - application: journalfoer-soeknad
          namespace: etterlatte
          cluster: prod-gcp
        - application: sjekk-adressebeskyttelse
          namespace: etterlatte
          cluster: prod-gcp
        - application: etterlatte-institusjonsopphold
          namespace: etterlatte
          cluster: prod-gcp
        - application: etterlatte-tilbakekreving
          namespace: etterlatte
          cluster: prod-gcp