apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ey-pdfgen
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
  liveness:
    path: /is_alive
  readiness:
    path: /is_alive
  prometheus:
    enabled: true
    path: /prometheus
  accessPolicy:
    inbound:
      rules:
        - application: journalfoer-soeknad
