apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ey-pdfgen
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 320Mi
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  prometheus:
    enabled: true
    path: /prometheus
  accessPolicy:
    inbound:
      rules:
        - application: journalfoer-soeknad
