name: .deploy.yaml

on:
  workflow_call:
    inputs:
      image:
        description: 'Lenke til docker image'
        required: true
        type: string
      cluster:
        description: 'Cluster. gcp eller fss'
        required: true
        type: string

jobs:
  deploy-to-dev-cluster:
    name: dev-cluster
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-${{ inputs.cluster }}
          RESOURCE: apps/${{ github.workflow }}/.nais/dev.yaml
          VAR: image=${{ inputs.image }}

  deploy-to-prod-cluster:
    name: prod-cluster
    if: ${{ github.ref == 'refs/heads/main' || github.event.inputs.deploy-prod == 'true' }}
    needs: deploy-to-dev-cluster
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: andstor/file-existence-action@v3
        id: check_files
        with:
          files: "apps/${{ github.workflow }}/.nais/prod.yaml"
      - uses: nais/deploy/actions/deploy@v2
        if: steps.check_files.outputs.files_exists == 'true'
        env:
          CLUSTER: prod-${{ inputs.cluster }}
          RESOURCE: apps/${{ github.workflow }}/.nais/prod.yaml
          VAR: image=${{ inputs.image }}
