name: bygg-tjenestespesifikasjoner

on:
  workflow_dispatch: # Allow manually triggered workflow run
  push:
    branches:
      - '**'
    paths:
      - tjenestespesifikasjoner/**
  pull_request:
    branches:
      - main
    paths:
      - tjenestespesifikasjoner/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # ratchet:actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Build with Maven
        run: mvn -f tjenestespesifikasjoner -B install
