name: ey-slackbot

on:
  workflow_dispatch: # Allow manually triggered workflow run
  push:
    branches:
      - main
    paths:
      - apps/ey-slackbot/**

jobs:
  build:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/.build-frontend.yaml
    secrets: inherit
    permissions:
      contents: 'read'
      id-token: 'write'

  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    uses: ./.github/workflows/.deploy.yaml
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: 'gcp'
    secrets: inherit
