name: Verify branches

on:
  push:
    branches-ignore:
      - main

jobs:
  verify-branches:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17.x
          cache: gradle

      # Build
      - name: Run Gradle Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew check
