name: Verify branches

on:
  push:
    branches-ignore:
      - main

jobs:
  verify-branches:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.gradlekey }}
          dependency-graph: generate-and-submit

      # Build
      - name: Run Gradle Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew check --configuration-cache