name: Verify branches

on:
  push:
    branches-ignore:
      - main
      - feature/slackbot

jobs:
  verify-branches:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16.x'

      # Build
      - name: Run Gradle Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew check
